import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import {
  buildEffectiveRunSessionConfigMetadata,
  normalizeModelProfileForSessionFingerprint,
  resolveTaskSessionConfigFreshness,
} from "../services/heartbeat.ts";

type SessionConfigInput = Parameters<typeof buildEffectiveRunSessionConfigMetadata>[0];
type SessionConfigMetadata = Awaited<ReturnType<typeof buildEffectiveRunSessionConfigMetadata>>;

// Model-profile metadata exactly as modelProfileRunMetadata() records it.
const DISABLED_CHEAP_REQUEST = {
  requested: "cheap",
  requestedBy: "wake_context",
  applied: null,
  configSource: null,
  fallbackReason: "agent_runtime_profile_disabled",
};
const UNSUPPORTED_CHEAP_REQUEST = {
  requested: "cheap",
  requestedBy: "issue_override",
  applied: null,
  configSource: null,
  fallbackReason: "adapter_profile_not_supported",
};
const APPLIED_CHEAP = {
  requested: "cheap",
  requestedBy: "wake_context",
  applied: "cheap",
  configSource: "agent_runtime",
  fallbackReason: null,
};
const BASE_ADAPTER_CONFIG = { command: "codex", model: "gpt-5.4-mini" };
const CHEAP_ADAPTER_CONFIG = { command: "codex", model: "gpt-5.4-nano" };

function sessionInput(overrides: Partial<SessionConfigInput> = {}): SessionConfigInput {
  return {
    adapterType: "codex_local",
    effectiveAdapterConfig: BASE_ADAPTER_CONFIG,
    agentRuntimeConfig: { heartbeat: { maxConcurrentRuns: 1 } },
    modelProfile: null,
    issueOverrides: null,
    workspaceConfig: { requestedMode: "agent_default", effectiveMode: "agent_default" },
    environment: { selectionSource: "default", selectedEnvironmentId: "environment-1" },
    environmentEnv: null,
    projectEnv: null,
    routineEnv: null,
    secretManifest: [
      {
        configPath: "env.OPENAI_API_KEY",
        envKey: "OPENAI_API_KEY",
        secretId: "secret-1",
        bindingId: "binding-1",
        version: 7,
        provider: "local_encrypted",
        outcome: "success",
      },
    ],
    runtimeSkills: [{ key: "paperclip", runtimeName: "paperclip", currentVersionId: "skill-version-1" }],
    agentConfigRevision: { id: "agent-config-revision-1", changedKeys: ["adapterConfig"] },
    ...overrides,
  };
}

function storedSessionParams(stored: { fingerprint: string; categoryFingerprints: Record<string, string> }) {
  return {
    sessionId: "thread-1",
    __paperclipConfiguredModel: "gpt-5.4-mini",
    __paperclipConfigFingerprint: stored.fingerprint,
    __paperclipConfigFingerprintVersion: 1,
    __paperclipConfigCategories: Object.keys(stored.categoryFingerprints),
    __paperclipConfigCategoryFingerprints: stored.categoryFingerprints,
  };
}

function freshness(stored: { fingerprint: string; categoryFingerprints: Record<string, string> }, next: SessionConfigMetadata, configuredModel = "gpt-5.4-mini") {
  return resolveTaskSessionConfigFreshness({
    hasTaskSession: true,
    configuredModel,
    taskSessionParams: { ...storedSessionParams(stored), __paperclipConfiguredModel: configuredModel },
    configMetadata: next,
  });
}

// Fingerprints that paperclipai 2026.824.1 (before normalization) persisted for
// sessionInput() with the given model-profile metadata. Generated by running
// buildEffectiveRunSessionConfigMetadata from the v2026.824.1 source.
const LEGACY_824_1 = {
  noRequest: {
    fingerprint: "v1:sha256:d9b8346bc89a7cbadd7d467db286011088bdcd192ea557a7fd0be691800e0ca6",
    categoryFingerprints: {
      adapter: "v1:sha256:26a88b5b4e1ce1187ea8c13792fcfcda5341aeb871a909c0d09046e45c559e93",
      adapterConfig: "v1:sha256:1cd82760f6131641f927221d1a2277d8fee2b0711b596c9d576b6357bdfb3d1a",
      agentRuntimeConfig: "v1:sha256:3c37c19f6928661cb205435737aa3283039119567a08df6d1a06c7e785326594",
      modelProfile: "v1:sha256:f11655d55dc1386d8b31a125dc6515e7f2f30bdc96dabaf4ce16ca76aefe3bac",
      instructions: "v1:sha256:8ab53c8385958d7cc11bcd9833f77cb82f02f6b4061954c5ac2cf9d27630d4f6",
      issueOverrides: "v1:sha256:54a9d829899ea51ff0fa3b2b7ce8fa0e3f5b46b26862931646c05cc2bb623b48",
      workspaceConfig: "v1:sha256:87ad4c71267023b42e84e171c4aecb5b2f1ba239a4cbb6ea09f0dc5ec1301d8d",
      environment: "v1:sha256:8c0af7b82ae25472fc73e3e03251d2c671f1d51a251a1ab35d3807410cef8a94",
      envBindings: "v1:sha256:b070c54c194f7b9edc53976cfbb766dd30f0df9e1c52f360b160adfacb9909d6",
      secrets: "v1:sha256:65d3dc5cc91f9076003b489701585236e7f54e68c5cdfa08b625a4536b4b7f96",
      runtimeSkills: "v1:sha256:695373984ea09196f7bfac45c992ea04c8bf1a70dcc5bcbec48ef3c025cfe47e"
    }
  },
  disabledRequest: {
    fingerprint: "v1:sha256:e6ea59b13cbc17935157787f08690e962d8410b9fbfaa992d1e554b88b02ef44",
    categoryFingerprints: {
      adapter: "v1:sha256:26a88b5b4e1ce1187ea8c13792fcfcda5341aeb871a909c0d09046e45c559e93",
      adapterConfig: "v1:sha256:1cd82760f6131641f927221d1a2277d8fee2b0711b596c9d576b6357bdfb3d1a",
      agentRuntimeConfig: "v1:sha256:3c37c19f6928661cb205435737aa3283039119567a08df6d1a06c7e785326594",
      modelProfile: "v1:sha256:a71ba805d15275a2c64dd131a6effa17dbb8519341d503d872e819274681ad09",
      instructions: "v1:sha256:8ab53c8385958d7cc11bcd9833f77cb82f02f6b4061954c5ac2cf9d27630d4f6",
      issueOverrides: "v1:sha256:54a9d829899ea51ff0fa3b2b7ce8fa0e3f5b46b26862931646c05cc2bb623b48",
      workspaceConfig: "v1:sha256:87ad4c71267023b42e84e171c4aecb5b2f1ba239a4cbb6ea09f0dc5ec1301d8d",
      environment: "v1:sha256:8c0af7b82ae25472fc73e3e03251d2c671f1d51a251a1ab35d3807410cef8a94",
      envBindings: "v1:sha256:b070c54c194f7b9edc53976cfbb766dd30f0df9e1c52f360b160adfacb9909d6",
      secrets: "v1:sha256:65d3dc5cc91f9076003b489701585236e7f54e68c5cdfa08b625a4536b4b7f96",
      runtimeSkills: "v1:sha256:695373984ea09196f7bfac45c992ea04c8bf1a70dcc5bcbec48ef3c025cfe47e"
    }
  },
  appliedProfile: {
    fingerprint: "v1:sha256:2ba283273bc7fa4689a375a8e6ffbf3a78677bf631aef89dce678f0cc7625bc3",
    categoryFingerprints: {
      adapter: "v1:sha256:26a88b5b4e1ce1187ea8c13792fcfcda5341aeb871a909c0d09046e45c559e93",
      adapterConfig: "v1:sha256:c33df659699f902af2df4aedcc7782168c50bb367f05521bec3d970fd3a96442",
      agentRuntimeConfig: "v1:sha256:3c37c19f6928661cb205435737aa3283039119567a08df6d1a06c7e785326594",
      modelProfile: "v1:sha256:5e11f13e31d6134dc2b4396495e664ffb2378273f19e7baab3374e38001d6c24",
      instructions: "v1:sha256:8ab53c8385958d7cc11bcd9833f77cb82f02f6b4061954c5ac2cf9d27630d4f6",
      issueOverrides: "v1:sha256:54a9d829899ea51ff0fa3b2b7ce8fa0e3f5b46b26862931646c05cc2bb623b48",
      workspaceConfig: "v1:sha256:87ad4c71267023b42e84e171c4aecb5b2f1ba239a4cbb6ea09f0dc5ec1301d8d",
      environment: "v1:sha256:8c0af7b82ae25472fc73e3e03251d2c671f1d51a251a1ab35d3807410cef8a94",
      envBindings: "v1:sha256:b070c54c194f7b9edc53976cfbb766dd30f0df9e1c52f360b160adfacb9909d6",
      secrets: "v1:sha256:65d3dc5cc91f9076003b489701585236e7f54e68c5cdfa08b625a4536b4b7f96",
      runtimeSkills: "v1:sha256:695373984ea09196f7bfac45c992ea04c8bf1a70dcc5bcbec48ef3c025cfe47e"
    }
  }
};

describe("session fingerprint model-profile normalization", () => {
  const tempDirs: string[] = [];
  afterAll(() => {
    for (const dir of tempDirs) rmSync(dir, { recursive: true, force: true });
  });

  it("keeps only the applied profile in the fingerprint category", () => {
    expect(normalizeModelProfileForSessionFingerprint(null)).toBeNull();
    expect(normalizeModelProfileForSessionFingerprint(DISABLED_CHEAP_REQUEST)).toBeNull();
    expect(normalizeModelProfileForSessionFingerprint(UNSUPPORTED_CHEAP_REQUEST)).toBeNull();
    expect(normalizeModelProfileForSessionFingerprint(APPLIED_CHEAP)).toEqual({
      applied: "cheap",
      configSource: "agent_runtime",
    });
  });

  it("does not fork the session for a disabled or unsupported profile request", async () => {
    const base = await buildEffectiveRunSessionConfigMetadata(sessionInput());
    for (const request of [DISABLED_CHEAP_REQUEST, UNSUPPORTED_CHEAP_REQUEST]) {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput({ modelProfile: request }));
      expect(next.fingerprint, request.fallbackReason).toBe(base.fingerprint);
      expect(next.categoryFingerprints).toEqual(base.categoryFingerprints);
      expect(freshness(base, next)).toMatchObject({ reset: false, changedCategories: [] });
    }
  });

  it("still resets when a profile is actually applied", async () => {
    const base = await buildEffectiveRunSessionConfigMetadata(sessionInput());
    const applied = await buildEffectiveRunSessionConfigMetadata(sessionInput({
      modelProfile: APPLIED_CHEAP,
      effectiveAdapterConfig: CHEAP_ADAPTER_CONFIG,
    }));
    const decision = freshness(base, applied, "gpt-5.4-nano");
    expect(decision.reset).toBe(true);
    expect(decision.changedCategories).toEqual(expect.arrayContaining(["modelProfile", "adapterConfig"]));
  });

  it("does not mask real configuration changes behind an ignored profile request", async () => {
    const instructionsRoot = mkdtempSync(path.join(tmpdir(), "paperclip-fingerprint-instructions-"));
    tempDirs.push(instructionsRoot);
    writeFileSync(path.join(instructionsRoot, "AGENTS.md"), "v1 instructions");
    const instructionsConfig = {
      ...BASE_ADAPTER_CONFIG,
      instructionsRootPath: instructionsRoot,
      instructionsEntryFile: "AGENTS.md",
    };
    const instructionsBase = await buildEffectiveRunSessionConfigMetadata(
      sessionInput({ effectiveAdapterConfig: instructionsConfig }),
    );
    writeFileSync(path.join(instructionsRoot, "AGENTS.md"), "v2 instructions");

    const base = await buildEffectiveRunSessionConfigMetadata(sessionInput());
    const cases: Array<{ name: string; category: string; stored: SessionConfigMetadata; input: Partial<SessionConfigInput> }> = [
      { name: "model", category: "adapterConfig", stored: base, input: { effectiveAdapterConfig: CHEAP_ADAPTER_CONFIG } },
      {
        name: "reasoning effort",
        category: "adapterConfig",
        stored: base,
        input: { effectiveAdapterConfig: { ...BASE_ADAPTER_CONFIG, modelReasoningEffort: "high" } },
      },
      {
        name: "issue effort override",
        category: "issueOverrides",
        stored: base,
        input: { issueOverrides: { adapterConfig: { modelReasoningEffort: "high" } } },
      },
      {
        name: "permissions",
        category: "adapterConfig",
        stored: base,
        input: { effectiveAdapterConfig: { ...BASE_ADAPTER_CONFIG, dangerouslyBypassApprovalsAndSandbox: true } },
      },
      { name: "instructions content", category: "instructions", stored: instructionsBase, input: { effectiveAdapterConfig: instructionsConfig } },
      {
        name: "tools / runtime skills",
        category: "runtimeSkills",
        stored: base,
        input: { runtimeSkills: [{ key: "paperclip", runtimeName: "paperclip", currentVersionId: "skill-version-2" }] },
      },
      {
        name: "environment",
        category: "environment",
        stored: base,
        input: { environment: { selectionSource: "default", selectedEnvironmentId: "environment-2" } },
      },
      { name: "environment env", category: "envBindings", stored: base, input: { projectEnv: { NEW_FLAG: "1" } } },
      {
        name: "secret version",
        category: "secrets",
        stored: base,
        input: {
          secretManifest: [
            {
              configPath: "env.OPENAI_API_KEY",
              envKey: "OPENAI_API_KEY",
              secretId: "secret-1",
              bindingId: "binding-1",
              version: 8,
              provider: "local_encrypted",
              outcome: "success",
            },
          ],
        },
      },
      {
        name: "workspace / trust isolation",
        category: "workspaceConfig",
        stored: base,
        input: { workspaceConfig: { requestedMode: "isolated_workspace", effectiveMode: "isolated_workspace" } },
      },
    ];

    for (const testCase of cases) {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput({
        ...testCase.input,
        modelProfile: DISABLED_CHEAP_REQUEST,
      }));
      const decision = freshness(testCase.stored, next);
      expect(decision.reset, testCase.name).toBe(true);
      expect(decision.changedCategories, testCase.name).toContain(testCase.category);
      expect(decision.changedCategories, testCase.name).not.toContain("modelProfile");
    }
  });

  describe("sessions checkpointed by 2026.824.1", () => {
    it("keeps the common no-request fingerprint byte-identical", async () => {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput());
      expect(next.fingerprint).toBe(LEGACY_824_1.noRequest.fingerprint);
      expect(next.categoryFingerprints).toEqual(LEGACY_824_1.noRequest.categoryFingerprints);
    });

    it("resumes a legacy session when a disabled request is now present (the reported reset)", async () => {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput({ modelProfile: DISABLED_CHEAP_REQUEST }));
      expect(freshness(LEGACY_824_1.noRequest, next)).toMatchObject({ reset: false, changedCategories: [] });
    });

    it("resumes a legacy session created under the same disabled request", async () => {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput({ modelProfile: DISABLED_CHEAP_REQUEST }));
      expect(next.fingerprint).not.toBe(LEGACY_824_1.disabledRequest.fingerprint);
      expect(freshness(LEGACY_824_1.disabledRequest, next)).toMatchObject({ reset: false, changedCategories: [] });
    });

    it("resumes a legacy session created under the same applied profile", async () => {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput({
        modelProfile: APPLIED_CHEAP,
        effectiveAdapterConfig: CHEAP_ADAPTER_CONFIG,
      }));
      expect(next.fingerprint).not.toBe(LEGACY_824_1.appliedProfile.fingerprint);
      expect(freshness(LEGACY_824_1.appliedProfile, next, "gpt-5.4-nano")).toMatchObject({
        reset: false,
        changedCategories: [],
      });
    });

    it("still resets a legacy applied-profile session when the profile is no longer applied", async () => {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput());
      const decision = freshness(LEGACY_824_1.appliedProfile, next);
      expect(decision.reset).toBe(true);
      expect(decision.changedCategories).toEqual(expect.arrayContaining(["modelProfile", "adapterConfig"]));
    });

    it("reports only the real change for a legacy disabled-request session", async () => {
      const next = await buildEffectiveRunSessionConfigMetadata(sessionInput({
        modelProfile: DISABLED_CHEAP_REQUEST,
        effectiveAdapterConfig: CHEAP_ADAPTER_CONFIG,
      }));
      const decision = freshness(LEGACY_824_1.disabledRequest, next);
      expect(decision.reset).toBe(true);
      expect(decision.changedCategories).toEqual(["adapterConfig"]);
    });
  });
});
